### PR TITLE
Add devcert

### PR DESCRIPTION
**Pull request by SarasArya**
I have added a package called `devcert`. Which creates ssl certs on the fly. All you have to do is, while you run the app for the first time, it will prompt you for a password. Enter your system password and voila. You will have certs in your proxy folder.

### CODE REVIEW

**Comment by SarasArya** [comment]
Hey @kristoferbaxter any comments on the same?

**Comment by kristoferbaxter** [comment]
Awesome! I'll take a look at the dependencies.

**Comment by kristoferbaxter** [comment]
Looks great. Will use the same approach for both preact-hn and react-hn.

https://github.com/kristoferbaxter/preact-hn/pull/30

**Comment by kristoferbaxter** [comment]
Expect to merge tonight.

**Comment by kristoferbaxter** [comment]
Merged these changes with https://github.com/kristoferbaxter/react-hn/commit/4b5278ba1328dcf8160ad7d7d81c743814666af9.

Closing issue! Thanks for the awesome work.

**Pull request closed without merging**
